version: '3.8'

services:
  dbtest:
    image: postgres:13
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ./testdata:/docker-entrypoint-initdb.d # Mount the testdata directory

volumes:
  postgres_data_test:
